"""Project data: the single source for the cards on index.html and the community pages."""

PROJECTS = [
    {
        "slug": "skyline-haven",
        "name": "Skyline Haven",
        "city": "Austin, TX",
        "area": "Downtown Austin",
        "type": "Urban Apartments",
        "status": "ongoing",
        "progress": 68,
        "eta": "Q3 2027",
        "price": "$425,000",
        "beds": "1–3 beds",
        "size": "520–1,480 sq ft",
        "homes": "142 apartments",
        "image": "project1.webp",
        "alt": "Glass residential tower with green terraces against a city skyline",
        "coords": (30.2672, -97.7431),
        "card": "A skyline-defining structure crafted for modern city dwellers — open layouts, green terraces, and panoramic glass bringing the horizon inside.",
        "tagline": "Open-plan apartments with green terraces and panoramic glass, in the middle of downtown Austin.",
        "overview": [
            "Skyline Haven is a 26-story residential tower of studios, one-, two- and three-bedroom apartments. Every home has floor-to-ceiling glass, a private balcony or terrace, and a layout designed around natural light and cross-ventilation.",
            "Shared spaces are built for everyday use: a landscaped podium garden, a rooftop pool, a co-working lounge and a fitness studio. A concierge team is on site around the clock.",
        ],
        "highlights": [
            "Floor-to-ceiling glass and private terraces",
            "Rooftop pool and landscaped podium garden",
            "Co-working lounge and fitness studio",
            "EV charging and secure bike storage",
            "24/7 concierge and package room",
            "Smart locks and thermostats in every home",
        ],
        "nearby": [
            ("Congress Avenue dining and shops", "4 min walk"),
            ("Lady Bird Lake trail", "6 min walk"),
            ("MetroRail station", "8 min walk"),
            ("Austin-Bergstrom Airport", "18 min drive"),
        ],
        "milestones": [
            ("Land and permits", "done", "Done · Q2 2024"),
            ("Foundation", "done", "Done · Q4 2024"),
            ("Structure", "done", "Done · Q3 2025"),
            ("Façade and systems", "current", "In progress"),
            ("Interiors", "todo", "Planned · Q1 2027"),
            ("Handover", "todo", "Planned · Q3 2027"),
        ],
        "types": [
            ("Studio", "0", "1", "520", "$425,000", "Limited"),
            ("One-bedroom", "1", "1", "710", "$489,000", "Available"),
            ("Two-bedroom", "2", "2", "1,080", "$639,000", "Available"),
            ("Three-bedroom penthouse", "3", "2.5", "1,480", "$899,000", "Waitlist"),
        ],
    },
    {
        "slug": "the-atria-tower",
        "name": "The Atria Tower",
        "city": "Chicago, IL",
        "area": "West Loop, Chicago",
        "type": "Mixed-Use High-Rise",
        "status": "completed",
        "progress": 100,
        "eta": "Completed 2025",
        "price": "$610,000",
        "beds": "0–3 beds",
        "size": "640–1,950 sq ft",
        "homes": "212 apartments",
        "image": "project3.webp",
        "alt": "Mixed-use glass high-rise in an urban setting",
        "coords": (41.8827, -87.6475),
        "card": "An urban statement of glass and geometry — combining luxury apartments, coworking spaces, and curated retail experiences.",
        "tagline": "Luxury apartments above coworking and retail, one block from the West Loop's restaurant row.",
        "overview": [
            "The Atria Tower combines 212 apartments with a street-level retail podium and two floors of coworking space. Residents live above a neighborhood that already has everything: restaurants, markets and the commuter train.",
            "Homes range from compact loft studios to three-bedroom sky residences with corner views. The building is finished and occupied, and a handful of homes are still available to move into right away.",
        ],
        "highlights": [
            "Retail podium and on-site coworking floors",
            "Sky lounge with city views",
            "Fitness center and resident terrace",
            "Heated underground parking with EV charging",
            "Bike room and dog wash",
            "Move-in ready homes available now",
        ],
        "nearby": [
            ("Randolph Street restaurant row", "5 min walk"),
            ("Union Station", "10 min walk"),
            ("Chicago Riverwalk", "12 min walk"),
            ("O’Hare Airport", "28 min drive"),
        ],
        "milestones": [
            ("Land and permits", "done", "Done · Q1 2021"),
            ("Foundation", "done", "Done · Q4 2021"),
            ("Structure", "done", "Done · Q2 2023"),
            ("Façade and systems", "done", "Done · Q1 2024"),
            ("Interiors", "done", "Done · Q4 2024"),
            ("Handover", "done", "Done · Q2 2025"),
        ],
        "types": [
            ("Loft studio", "0", "1", "640", "$610,000", "Move-in ready"),
            ("One-bedroom", "1", "1", "860", "$720,000", "Move-in ready"),
            ("Two-bedroom", "2", "2", "1,320", "$985,000", "Few left"),
            ("Three-bedroom sky residence", "3", "3", "1,950", "$1,190,000", "Waitlist"),
        ],
    },
    {
        "slug": "coastline-residences",
        "name": "Coastline Residences",
        "city": "Charleston, SC",
        "area": "James Island, Charleston",
        "type": "Luxury Seaside Villas",
        "status": "ongoing",
        "progress": 42,
        "eta": "Q1 2028",
        "price": "$895,000",
        "beds": "3–5 beds",
        "size": "2,100–3,600 sq ft",
        "homes": "36 villas",
        "image": "project2.webp",
        "alt": "Seaside villas with private decks facing the Atlantic",
        "coords": (32.7137, -79.9693),
        "card": "Set along the Atlantic edge, this project merges elegance with serenity — private decks, sea-view lounges, and natural textures throughout.",
        "tagline": "Thirty-six villas with private decks and sea views, set along the Atlantic edge.",
        "overview": [
            "Coastline Residences is a small community of 36 villas on the water. Each home has a deep private deck, large sliding glass walls and natural materials — timber, stone and lime plaster — chosen to age well in a coastal climate.",
            "Villas are raised and built to current flood standards. Residents share a sea-view lounge, a private dock and landscaped walking paths that run the length of the site.",
        ],
        "highlights": [
            "Private decks with sea views",
            "Residents’ dock and sea-view lounge",
            "Flood-resilient raised construction",
            "Natural timber, stone and lime-plaster finishes",
            "Smart-home wiring and EV charging in every garage",
            "Landscaped walking paths along the shoreline",
        ],
        "nearby": [
            ("Residents’ dock and marina", "3 min walk"),
            ("Folly Beach", "12 min drive"),
            ("Charleston Historic District", "15 min drive"),
            ("Charleston International Airport", "25 min drive"),
        ],
        "milestones": [
            ("Land and permits", "done", "Done · Q1 2025"),
            ("Foundation", "done", "Done · Q4 2025"),
            ("Structure", "current", "In progress"),
            ("Façade and systems", "todo", "Planned · Q2 2027"),
            ("Interiors", "todo", "Planned · Q3 2027"),
            ("Handover", "todo", "Planned · Q1 2028"),
        ],
        "types": [
            ("Three-bedroom villa", "3", "3", "2,100", "$895,000", "Available"),
            ("Four-bedroom villa", "4", "3.5", "2,800", "$1,090,000", "Available"),
            ("Four-bedroom waterfront villa", "4", "4", "3,200", "$1,260,000", "Limited"),
            ("Five-bedroom waterfront estate", "5", "5", "3,600", "$1,400,000", "Waitlist"),
        ],
    },
    {
        "slug": "verdant-grove",
        "name": "Verdant Grove",
        "city": "Portland, OR",
        "area": "Southeast Portland",
        "type": "Eco-Living Residences",
        "status": "completed",
        "progress": 100,
        "eta": "Completed 2024",
        "price": "$540,000",
        "beds": "2–4 beds",
        "size": "1,100–2,200 sq ft",
        "homes": "88 townhomes",
        "image": "project4.webp",
        "alt": "Eco-living housing complex surrounded by greenery",
        "coords": (45.5122, -122.6587),
        "card": "A nature-inspired housing complex emphasizing green spaces, rainwater systems, and natural ventilation across all homes.",
        "tagline": "Eighty-eight low-energy townhomes arranged around shared gardens in Southeast Portland.",
        "overview": [
            "Verdant Grove is a neighborhood of 88 townhomes built around shared gardens and car-free lanes. Every home is designed for low running costs: solar-ready roofs, heat-pump heating and cooling, and rainwater harvesting for the gardens.",
            "Homes are naturally ventilated, with windows placed for cross-breezes and deep eaves for summer shade. The community is complete and lived in, with a few move-in ready homes still available.",
        ],
        "highlights": [
            "Solar-ready roofs and heat-pump heating and cooling",
            "Rainwater harvesting for shared gardens",
            "Community gardens and car-free lanes",
            "Naturally ventilated, shaded layouts",
            "EV charging and covered bike storage",
            "Move-in ready homes available now",
        ],
        "nearby": [
            ("Hawthorne dining and shops", "7 min walk"),
            ("MAX light-rail stop", "9 min walk"),
            ("Laurelhurst Park", "12 min walk"),
            ("Portland International Airport", "20 min drive"),
        ],
        "milestones": [
            ("Land and permits", "done", "Done · Q3 2021"),
            ("Foundation", "done", "Done · Q2 2022"),
            ("Structure", "done", "Done · Q1 2023"),
            ("Façade and systems", "done", "Done · Q3 2023"),
            ("Interiors", "done", "Done · Q1 2024"),
            ("Handover", "done", "Done · Q3 2024"),
        ],
        "types": [
            ("Two-bedroom townhome", "2", "2.5", "1,100", "$540,000", "Move-in ready"),
            ("Three-bedroom townhome", "3", "2.5", "1,640", "$690,000", "Move-in ready"),
            ("Four-bedroom family home", "4", "3", "2,200", "$845,000", "Few left"),
        ],
    },
]
